name: Get latest files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create commit message
        run: |
          ua="Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
          version=$(curl -sS -H "User-Agent: $ua" https://wplace.live/_app/version.json | jq -r '.version' || echo "unknown")
          echo "UPDATE_MESSAGE=Update latest files to version $version" >> $GITHUB_ENV

      - name: Fetch latest files
        run: bun run index.ts

      - name: Commit changes
        run: |
          git add .
          git commit -m "$UPDATE_MESSAGE" || echo "No changes to commit"
          git push origin master || echo "No changes to push"